version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: battle-coding-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: battle_coding
      MYSQL_USER: root
      MYSQL_PASSWORD: dbsl3861
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: battle-coding-app
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/battle_coding?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: dbsl3861
    ports:
      - "8080:8080"

volumes:
  mysql_data:
